### ISSUE TITLE
Security MVP: All images in management cluster must come from IBM Cloud registries (gap in catalog pods) and cannot be dynamic content (changes must come through Change request)

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#1075]
There are currently 4 images (the catalog sources) that come from a non IBM Cloud registry. They instead come from upstream redhat.io. This is not allowed from an IBM Cloud security perspective in our managed control plane. All images must be sourced from the regional IBM Cloud registry offerings in order to be compliant for a GA offering. Additionally: dynamic content is injected potentially on a restart of the pod (since it pulls from a constantly updating tag that is updated daily.) That has been flagged as a blocking security risk for our offering. 

There's two general approaches:
1) We could move the catalog pods back to being inside the customer cluster. That would put it out of our control-plane plane environment and into the guest environment. Then the package server uses konnectivity to ultimately talk to those pods. The cronjobs to rollout the pod updates would also need to move to the guest cluster. This keeps the standard Openshift architecture that has been approved for use.

2) We add support to be able to specify an image for the catalog content similar to the offline strategy. IBM Cloud handles mirroring from redhat.io on a regular interval to update content. The registry override field would need to be able to be accounted for for the catalog operator pods as well and we would also do image mirroring in the case of hypershift to point the specific operator packages

```
registry.redhat.io/redhat/redhat-marketplace-index
registry.redhat.io/redhat/redhat-operator-index
registry.redhat.io/redhat/certified-operator-index
registry.redhat.io/redhat/community-operator-index
```

To regional registries under the same name. However: in the compliance of our control-plane we cannot have anything dynamically go to production: Everything needs to be approved through a specific CHANGE record and needs to be able to go through a promotion pipeline (dev/prestage/stage/production) and have an auditable history of when a change was made. In order for this to occur we would need to be able to specify a sha or git commit of the specific version we are using at a moment in time and update that periodically over time.

**Comment by relyt0925** [comment]
I think the best strategy at this time might be to just keep them in the guest cluster but open to ideas

**Comment by rtheis** [comment]
Based on our experience running Red Hat OpenShift on IBM Cloud clusters the past few year, I think that stability of the catalog pods is less than desirable and would create an operational headache for us if they run in our managed control plane.  From a security and availability perspective, I think option 1 (move back to guest cluster) is our only viable option.

**Comment by rtheis** [comment]
> > I think that stability of the catalog pods is less than desirable
> 
> can you elaborate on this? what sort of stability issues have you seen? what bugs have been filed?
> 
> > From a security and availability perspective, I think option 1 (move back to guest cluster) is our only viable option.
> 
> alternatively you can just disable these 4 "Default" catalogs and instead define your own catalogsources(pointing to approved ibm registries), while still running them on the management cluster.
> 
> cc @joelanford @perdasilva

The primary problem that we have seen is the pods being in a non-running state due to them crashing or the container runtime being unable to pull the container images.  We have notified Red Hat of the problems on various occasions.  The latest report came through a severity 1 premium support case.  There are also times when we simply ignore the failures.  

Moving these components to the control plane would escalate the severity of the problems and we likely wouldn't be able to ignore the failures.  

The alternative to disable the default catalogs and defining our own catalogsources in the IBM approved registries would likely help address most of the problems.

**References:** 

- https://github.com/openshift/okd/issues/785
- https://access.redhat.com/support/cases/#/case/03161072

![image](https://user-images.githubusercontent.com/17885615/158247922-7cd69538-9a56-43a5-8a94-5ca12b9e7240.png)

**Comment by rtheis** [comment]
In our environment, this was a problem only for the default catalog pods.  We mirror all other images except the default catalog.  And both nodes were being lost and new clusters were being deployed during the outage so customers were hitting problems.  Should these catalog pods have been running in our control plane, the impacts would extended even further due to how we manage alerting and monitoring of the cluster control plane. 

I agree that moving between guest cluster and control plane just punts the problem and doesn't solve it. We do care about the problem either way, but often ignore the problem unless it yields an extended outage or impacts our testing.  The problem becomes more severe when it hits the control plane.  From our perspective, we need more control of the catalog and what it is doing before we can run it in the control plane.
