### ISSUE TITLE
ignition server authentication not work to add vm's after 24 hours

### ISSUE THREAD

**Issue by nadavdolin** [openshift/hypershift#1634]
Hello,

I have some issues with the hypershift.
I run a hypershift+kubevirt on a disconnected cluster
when I have a hosted cluster that runs fully complete on an infra cluster that disconnected network I want to scale up the worker so I add the number of replicas in the nodePool resource but in the console of the new VM that up I see that he try to get the ignition from the ignition-server pod but I get this error:
`GET result: Network Authentication Required`
it happened only after 24 hours that the cluster was up. 

infra OCP version: 4.10.16
cluster version that I try to up: 4.10.16

what more information i can provide to help you help me :)
Thanks!

**Comment by nadavdolin** [comment]
After a research i found where is the problem, there is in the hosted cluster namespace a secret that contain the name: *1* `user-data-"hostedClusterName"` and a secret: *2* `user-data-"hostedClusterName"-userdata`
I found that the *1* secret is refreshed to the new token authentication but the *2* secret is not and this is the secret that the VM is used to pull the ignition. i check if it something in the hypershift code but it not, so my guess is maybe the problem of the sysnc the secrets is in the kubevirt code.

what more information i can provide to help you help me :)
Thanks!

**Comment by raz-bn** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/issues/169
Issue I've opened on the kubevit provider repo. 

I think the sercret they are creating with the userdata is created because the key of the original userdata secret is "value" instead of "userdata". I would like to change the secret key to "userdata" and remove the creation of the secret from the kubevirt provider
